server:
  port: 800
spring:
  data:
    mongodb:
#      uri: mongodb://admin:123456@localhost:27017/test_one_db?authSource=admin
      authentication-database: admin
      host: localhost
      port: 27017
      database: test_one_db
      username: admin
      password: '123456'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。